# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
 adapter: postgresql
 pool: 5
 username: <%= ENV['POSTGRES_USER'] %>
 password: <%= ENV['POSTGRES_DB'] %>
 host: ''
 port: 5432

development:
 <<: *default
 database: <%= ENV['POSTGRES_DATABASE'] %>

test:
 <<: *default
 database: <%= ENV['POSTGRES_DATABASE_TEST'] %>

staging:
 <<: *default
 database: <%= ENV['POSTGRES_DATABASE'] %>

production:
 <<: *default
 database: <%= ENV['POSTGRES_DATABASE'] %>